### PR TITLE
Many small Fixes and update to Papagayo-ng

### PR DESCRIPTION
**Pull request by steveway**

### CODE REVIEW

**Comment by steveway** [comment]
Whoa, seems like my commit history is a bit out of whack. But the status of the files seems to be alright now. Sorry.

**Comment by steveway** [comment]
Update to most references Papagayo-ng

**Comment by morevnaproject** [comment]
Hello @steveway !
Thank you for the doing all this work! I have noticed that there are some files missing in your commits. For example, there is no papagayo-ng.py file - https://github.com/steveway/papagayo-ng/commit/42903767a6812f304721d8f7976e6ebb2b588499
I guess you have renamed "papagayo.py" to "papagayo-ng.py". As result, GIT treats "papagayo.py" as "deleted file" and "papagayo-ng.py" as "new file". You need to add "papagayo-ng.py" (and all others) file explicitly.

Also, please make sure to use "Papagayo-NG" in the source files instead of "Papagayo-ng". For filenames please keep everything in lowercase. 

Thank you! ^__^

**Comment by steveway** [comment]
Oh yes you are right! I'll add that back later today when I'm back from work. (Only a few hours from now)

**Comment by morevnaproject** [comment]
@steveway THank you for the changes! They are merged now!

 I believe you might want to do "git reset" for your branches to avoid messed look of git history ^__^ -
screenshot1

Here's the example for "testing" branch:
```
 git fetch upstream
 git checkout testing
 git reset --hard upstream/master
```

Be aware, that all changes not merged into upstream/master will be lost. S if you have unmerged commits it's better to go different way.

Thank you again!

**Pull request closed without merging**
