### PR TITLE
REFACTORING for wxPhoenix v.4+ and DEPRECIATING wxGlade

### PR DESCRIPTION
**Pull request by egoZentric**
Hej Guys.

I forked PPG-NG 1.4 . I bring wxPython expertise to the table. BUT this code base is really a big spageti mess. allow me to clean up and make it ready for further development,

As of now - this pull req - it runs on python 3.7 on a windows x64

\eZ

### CODE REVIEW

**Comment by steveway** [comment]
Hey, that is cool!
This project can use some clean-up.
It's great having people helping any tiny bit.
I had a quick look over the commits and it seems to look quite good.
So, if Konstantin likes this this will likely get merged.
Uhm, but there is a small but.
Most of the development is at the moment happening on the QT Port.
The development is pretty far advanced already.
But there is still a bit that needs to be done before the transition is complete.
So fixes and improvements to the wx version are still useful.
Just so you know when investing bigger chunks of time.

**Comment by morevnaproject** [comment]
Hello! I have  made a quick look at all changes and tested with Python2 / WxGtk3. Looks good!

I also like changes in Readme.txt file. @steveway I think it worth to copy contents of Readme to your QT Port branch.

Regarding future development of Papagayo-NG - yes, we are moving from wxWidgets to python-QT. It is very close to usable status and the future development is relevant there.   Please check this  therad - https://github.com/morevnaproject/papagayo-ng/issues/33
Any help with QT port is much appreciated. Thank you!

**Comment by morevnaproject** [comment]
I think we should keep "import gettext" and related _() function - https://github.com/morevnaproject/papagayo-ng/pull/48/files#diff-5ef6458f48b15dc67b7eff21401b3e13L23

_()function is not related to wxGlade. It is a functionality provided by gettext.
The localization should be provided according to instructions here - https://docs.python.org/3/library/gettext.html?highlight=gettext#localizing-your-application

**Comment by morevnaproject** [comment]
@egoZentric So, can you please revert commits 0109d2f9b3f and d65870f9ac1e6a, so I can merge your changes? We would like to keep gettext, as explained above.

**Comment by morevnaproject** [comment]
Closed because of inactivity.

**Pull request closed without merging**
