### PR TITLE
The big WaveformView Rewrite

### PR DESCRIPTION
**Pull request by steveway**
Well this is the rewritten Waveformview mostly.
This should be better than the current version in pretty much every aspect.
I do have a change here that I'm a bit unsure of, it does make sense:
Phrases and Words have now a minimum size, it's the number of phonemes for words and the combined minimum sizes of the contained words (so all belonging phonemes) for phrases.
Since a phoneme is fixed as 1 frame in size and only 1 phoneme per frame is allowed that makes only sense.
A person can't (normally) form two mouth-shapes at the same moment.
The edge cases would be two or more voices at the same time but for that we already support multiple voices, which should be able to overlap. (Haven't tested that myself actually.)

### CODE REVIEW

**Comment by morevnaproject** [comment]
- It would be nice to merge content of `requirements.txt` into `readme.txt`.

**Comment by steveway** [comment]
I've added it quickly using the webinterface of Github.
Now the readme has the current dependency information.
But a separate requirements.txt still makes sense because you can then use that to install the dependencies with one pip command.

**Comment by steveway** [comment]
The hang is very likely because QT is taking quite a lot of time when loading the sound file for the first time. So it hangs in the SoundPlayerQT.py file in the while loop at line 44.
We should be able to add some dialog or if we have progressinformation from QT maybe even that.
Idealy that blocking while loop will be removed and the rest of that code changed so that it can continue loading in the background.
That Jekyll thing is because I wanted to try out creating a simple page using github pages.
That would then be available via https://pages.github.com/steveway
Nothing important, just something I experimented with.

**Comment by steveway** [comment]
Also, the save reminder is wonky, but saving and loading itself seems to work.
FPS changing might also not work as expected.
And if you haven't noticed yet, it is now more strict about how small sentences/words are allowed to be.
It seems to be pretty difficult to escape these restraints. (Which is by design.)
A word must be able to contain all of it's phonemes, because 2 phonemes can't overlap and are 1 frame long. You can't make 2 shapes at the same time with one mouth.

**Comment by morevnaproject** [comment]
> Now the readme has the current dependency information.
But a separate requirements.txt still makes sense because you can then use that to install the dependencies with one pip command.

I plan to write a scripts to easily setup all required environment and packages for Windows/OSX/Linux platforms. ^__^

> That Jekyll thing is because I wanted to try out creating a simple page using github pages.
That would then be available via https://pages.github.com/steveway

I suggest to set up a separate repository for website, as many projects do.

Another idea - possibly it worth to create a GitHub organization called "Papagayo-NG" and move this repo there. In this case we will have a better permissions model, so you will get more powers on administrating project (currently it is tied to my user).

> EDIT: I think we should change the widget for the FPS to a QSpinBox, makes more sense for such a number input. I think I'll try to get the FPS working correctly next.

Great idea!

Actually this PR makes QT version really usable, much better than in previous state! I suggest to merge it already and create a separate issues about:

- [ ] file loading progressbar
- [ ]  FPS to a QSpinBox

Anything else I missed? ^__^

**Comment by steveway** [comment]
Alright, the FPS input is now a QSpinBox. I also tried getting changes to that implemented correctly.
But that doesn't yet work how I imagined it, currently it only changes the fps value of the project and via that the playback marker moves differently.
I'll have to look how this was implemented on the original wx version, if it was even working there.
After some testing, the longer wait time seems to be in the decode_audio method of the soundplayer. 
But QAudioDecoder doesn't seem to expose the current progress value.
So the QProgressDialog during that will not show the current Progress, but it's showing that it's doing something at least.

I also just remembered that scrubbing is not yet implemented, I've experimented a bit with that just a few days ago.
It's something for the Todo List.

**Comment by morevnaproject** [comment]
> I'll have to look how this was implemented on the original wx version, if it was even working there.

I remember it was working there. ^__^

I have made an issue about that (with video) - https://github.com/morevnaproject/papagayo-ng/issues/57

> So the QProgressDialog during that will not show the current Progress, but it's showing that it's doing something at least.

Yes, it is much better now!

> I also just remembered that scrubbing is not yet implemented, I've experimented a bit with that just a few days ago.

Added here - https://github.com/morevnaproject/papagayo-ng/issues/56

**Comment by morevnaproject** [comment]
Merged now. Thank you very much! ^__^

**Pull request merged**
